SC-251.2: Improve error handling; print tokens to browser window
Sage-Bionetworks/synapse-login-scipool pull request #75
Opened 2021-06-14 22:16 UTC by brucehoff

- direct browser to display returned tokens on screen rather than download to a file;
- improve error handling (e.g. a 4xx from Synapse is translated into a response from this service with the same HTTP status)

2021-06-14 22:54 UTC, zaro0508 requested changes
Looks good in general.  There are still comments and docs that refer to downloading files.  Can we update those as well?

2021-06-15 17:20 UTC, zaro0508 approved these changes

2021-06-15 17:20 UTC, zaro0508 commented on README.md
> +`/personalaccesstoken`: returns a long-lived 'personal access token' (PAT) for the user who has logged in to Synapse.  The token name in the Synapse console is 'AWS CLI for Service Catalog'.  If a PA
Can we request the PAT after login?   For example I want to do this workflow..

1. login to SC via syanpse idp on browser 
2. make a request in the terminal to get the PAT, i.e. curl https://sc-dev.sageit.org/personalaccesstoken

step #2 is the main reason why I requested to have the endpoints return txt/json instead of downloading a file.

2021-06-15 18:53 UTC, brucehoff commented on README.md
> +`/personalaccesstoken`: returns a long-lived 'personal access token' (PAT) for the user who has logged in to Synapse.  The token name in the Synapse console is 'AWS CLI for Service Catalog'.  If a PA
@zaro0508 You would do step 1 in your browser using the URL https://sc-dev.sageit.org/personalaccesstoken, this returns the PAT.  No step 2 is needed.  Will this meet your needs?

2021-06-15 18:54 UTC, merged